# Generated by Django 6.0.7 on 2026-07-27 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'db_table': 'Tag',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000)),
                ('image_url', models.URLField(blank=True, max_length=2000)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('content_text', models.TextField(blank=True)),
                ('reading_time_minutes', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('Unread', 'Unread'), ('Read', 'Read'), ('Archived', 'Archived')], default='Unread')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='read_it_later.tag')),
            ],
            options={
                'db_table': 'Article',
                'ordering': ['-created_at'],
                'managed': True,
                'unique_together': {('user', 'url')},
            },
        ),
    ]
