# Generated by Django 6.0.7 on 2026-07-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_it_later', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='fetch_failed',
            field=models.BooleanField(default=False),
        ),
    ]
